image: ruby:2.5.3

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
  - cd ./docs
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
